import type { Metadata } from "next";
import {
  LegalDocument,
  type LegalSection,
} from "@/components/legal/LegalDocument";

// The Terms URL is part of the App Store listing legal requirements, so this
// page must be crawlable — override the root layout's global no-index.
export const metadata: Metadata = {
  title: "Terms of Service — Wholesale Portal",
  description:
    "The terms governing use of Wholesale Portal, the Shopify-embedded B2B wholesale operating system.",
  robots: { index: true, follow: true },
};

const UPDATED = "July 8, 2026";

const sections: LegalSection[] = [
  {
    heading: "1. Agreement",
    blocks: [
      'These Terms of Service ("Terms") are a binding agreement between [Company Legal Name] ("we", "us") and the Shopify merchant that installs or uses Wholesale Portal ("the App", "you"). By installing or using the App you accept these Terms. If you do not agree, do not install or use the App.',
    ],
  },
  {
    heading: "2. The service",
    blocks: [
      "The App is a Shopify-embedded B2B wholesale operating system that provides tiered wholesale pricing, spreadsheet-style bulk ordering, self-serve buyer onboarding and approval, automated PDF invoicing, accounts receivable, and — where enabled — Buy-Now-Pay-Later financing through our third-party provider. Features may change over time as the App evolves.",
    ],
  },
  {
    heading: "3. Eligibility and accounts",
    blocks: [
      "You must have an active Shopify store and authority to bind your business to grant the App the Shopify permissions it requests. You are responsible for the accuracy of your account information, for your users (including sales representatives and buyers you approve), and for maintaining the confidentiality of credentials.",
    ],
  },
  {
    heading: "4. Your responsibilities",
    blocks: [
      "You are responsible for:",
      [
        "Configuring pricing tiers, catalog visibility, buyer approvals, and payment terms correctly for your business.",
        "The lawfulness of the buyer data you process and for providing your buyers with any required notices and rights.",
        "Your own compliance with tax, invoicing, consumer-protection, and export laws applicable to your wholesale operations.",
        "Reviewing invoices, orders, and receivables generated by the App before relying on them.",
      ],
    ],
  },
  {
    heading: "5. Fees and billing",
    blocks: [
      'Paid plans consist of a recurring subscription plus one-time usage charges for gross merchandise value ("GMV") processed above your plan’s included threshold. Billing is handled by our Merchant of Record, Paddle, which acts as the reseller and issues receipts and handles applicable taxes. By subscribing you also agree to Paddle’s buyer terms.',
      "Subscriptions renew automatically for successive periods until cancelled. You can view your plan and manage or cancel your subscription from the App’s billing settings; cancellation takes effect at the end of the current billing period. Except where required by law, fees already incurred (including usage charges) are non-refundable.",
    ],
  },
  {
    heading: "6. Buy-Now-Pay-Later",
    blocks: [
      "Where you enable BNPL, financing is provided by an independent third-party provider (Resolve) under its own agreement with the applicable party. We are not a lender, and we are not responsible for credit decisions, financing terms, or the collection of financed amounts. BNPL availability may be limited by region.",
    ],
  },
  {
    heading: "7. Acceptable use",
    blocks: [
      "You will not misuse the App, including by attempting to breach security or tenant isolation, accessing data of other merchants or buyers, reverse-engineering the service except as permitted by law, exceeding rate limits or interfering with availability, or using the App for unlawful purposes.",
    ],
  },
  {
    heading: "8. Intellectual property",
    blocks: [
      "We retain all rights in the App, including its software, design, and documentation. You retain all rights in your store data, catalog, and buyer data. You grant us a limited license to process that data solely to provide the App, as described in our Privacy Policy.",
    ],
  },
  {
    heading: "9. Third-party services",
    blocks: [
      "The App integrates with Shopify and other third-party services (hosting, storage, authentication, email, payments, financing, and monitoring). Your use of those services is subject to their terms, and we are not responsible for their acts or omissions.",
    ],
  },
  {
    heading: "10. Disclaimers",
    blocks: [
      'The App is provided "as is" and "as available" without warranties of any kind, whether express or implied, including merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the App will be uninterrupted, error-free, or that computed values will meet every accounting or regulatory requirement applicable to your business. The App is a tool, not accounting, tax, or legal advice.',
    ],
  },
  {
    heading: "11. Limitation of liability",
    blocks: [
      "To the maximum extent permitted by law, we will not be liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, revenue, data, or goodwill. Our aggregate liability arising out of or relating to the App will not exceed the amounts you paid for the App in the twelve (12) months preceding the claim.",
    ],
  },
  {
    heading: "12. Indemnification",
    blocks: [
      "You will indemnify and hold us harmless from claims arising out of your use of the App, your data, or your breach of these Terms, except to the extent caused by our own gross negligence or willful misconduct.",
    ],
  },
  {
    heading: "13. Suspension and termination",
    blocks: [
      "You may stop using the App at any time by uninstalling it from your Shopify admin; uninstalling triggers our data-cleanup process described in the Privacy Policy. We may suspend or terminate access for material breach, security risk, non-payment, or where required by law. Sections that by their nature should survive termination (fees incurred, intellectual property, disclaimers, limitation of liability, and indemnification) will survive.",
    ],
  },
  {
    heading: "14. Changes to these Terms",
    blocks: [
      'We may update these Terms; material changes will be reflected by the "Last updated" date above and, where appropriate, in-app notice. Your continued use after changes take effect constitutes acceptance.',
    ],
  },
  {
    heading: "15. Governing law and contact",
    blocks: [
      "These Terms are governed by the laws of [Jurisdiction], without regard to conflict-of-laws rules, and the courts of [Jurisdiction] will have exclusive jurisdiction, except where applicable law provides otherwise. Questions? Contact support@yourdomain.com.",
    ],
  },
];

export default function TermsOfServicePage(): JSX.Element {
  return (
    <LegalDocument
      title="Terms of Service"
      updated={UPDATED}
      crossLink={{ href: "/privacy", label: "Privacy Policy" }}
      intro={
        <>
          <p className="rounded-lg border border-warning-border bg-warning-bg px-4 py-3 text-sm text-warning">
            Template notice: complete the bracketed placeholders (legal entity,
            jurisdiction) and have this reviewed by counsel before publishing.
            It reflects how the App actually operates, but it is not legal
            advice.
          </p>
          <p>
            These Terms govern your installation and use of Wholesale Portal.
            Please read them alongside our Privacy Policy.
          </p>
        </>
      }
      sections={sections}
    />
  );
}
